Repository Sarita-021/e-Book-Store, pull requests merged in 2025-02, with the labels that each got.

#27 Made About Page Responsive
  client/src/CSS/about.css
  client/src/pages/about.js
Labels: jwoc, medium

#30 implemented order functionality with backend
  client/src/CSS/book.css
  client/src/components/App.js
  client/src/pages/OTPInput.js
  client/src/pages/allbooks.js
  client/src/pages/book.js
  client/src/pages/collection.js
  client/src/pages/login.js
  client/src/pages/navbar.js
  client/src/pages/order.js
  client/src/pages/register.js
  server/controllers/orderController.js
  server/index.js
  server/models/cartModel.js
  server/models/orderModel.js
  server/routes/orderRoutes.js
Labels: hard, JWOC 2025

#33 Added scrollbar and dark mode on testimonial
  client/src/CSS/index.css
  client/src/CSS/testimonial.css
  client/src/pages/home.js
Labels: easy, JWOC 2025

#40 Added Redirect link
  client/src/CSS/navbar.css
  client/src/pages/navbar.js
Labels: easy, JWOC 2025

#38 added a scroll to top button
  client/src/components/App.js
  client/src/components/ScrollToTopButton.jsx
  package-lock.json
Labels: easy, JWOC 2025

#42 Done with the issue #29
  client/src/CSS/faqpage.css
  client/src/components/App.js
  client/src/pages/FaqPage.js
  client/src/pages/navbar.js
Labels: medium, JWOC 2025

#41 search bar ui updated
  client/src/CSS/allbooks.css
  client/src/pages/allbooks.js
Labels: easy, JWOC 2025

#46 faq page changes
  client/src/CSS/faqpage.css
  client/src/components/App.js
  client/src/pages/FaqPage.js
  client/src/pages/navbar.js
Labels: medium, JWOC 2025
